version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 678878256416.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=678878256416.dkr.ecr.us-east-1.amazonaws.com/sastaticket
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t sastaticket:latest -f "${Dockerfile}" .
      - docker tag sastaticket:latest 678878256416.dkr.ecr.us-east-1.amazonaws.com/sastaticket:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/sastaticket:latest
      - echo Writing image definitions file...
      - printf '[{"dsapi":"%s","imageUri":"%s"}]' dsapi $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
